public class Odoo_InvoiceWrapper {
		public String invoice_date_due{get;set;}
		public list<String> invoice_line_ids{get;set;}
		public Boolean invoice_date{get;set;}
		public Integer journal_id{get;set;}
		public Integer id{get;set;}
		public String name{get;set;}
		public Boolean delivery_date{get;set;}
		public Integer partner_id{get;set;}
		public String name_X{get;set;}
		public Boolean partner_shipping_id{get;set;}
		public String model{get;set;}
}